# Generated by Django 3.1.7 on 2021-03-15 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='paid',
        ),
        migrations.AddField(
            model_name='invoice',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='_db.account'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_from',
            field=models.DateField(null=True, verbose_name='Дата с'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_to',
            field=models.DateField(null=True, verbose_name='Дата по'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('Оплачена', 'Оплачена'), ('Частично оплачена', 'Частично оплачена'), ('неоплачена', 'неоплачена')], max_length=55, null=True, verbose_name='Статус квитанции'),
        ),
    ]
