# Generated by Django 3.1.7 on 2021-03-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0002_auto_20210315_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitemainpageblocks',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websitemainpageblocks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='websitemainpageblocks',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
