# Generated by Django 3.1.7 on 2021-03-17 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0004_auto_20210317_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tariff',
            field=models.CharField(choices=[('Основной', 'Основной'), ('Пенсионный', 'Пенсионный'), ('Дополнительный', 'Дополнительный')], max_length=55, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('Оплачена', 'Оплачена'), ('Частично оплачена', 'Частично оплачена'), ('Неоплачена', 'Неоплачена')], max_length=55, null=True, verbose_name='Статус квитанции'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seo',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seo',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='account',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='_db.account', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.IntegerField(blank=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='manager',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_manager', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='payment_made',
            field=models.BooleanField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_db.transfertype', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_user', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
