# Generated by Django 3.1.7 on 2021-03-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0005_auto_20210317_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteserviceblocks',
            name='seo',
        ),
        migrations.AlterField(
            model_name='websiteservice',
            name='seo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='_db.seo'),
        ),
        migrations.AlterField(
            model_name='websiteserviceblocks',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websiteserviceblocks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='websiteserviceblocks',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
