# Generated by Django 3.1.7 on 2021-03-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0006_auto_20210321_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfertype',
            name='transfer_income',
            field=models.CharField(choices=[('Приход', 'Приход'), ('Расход', 'Расход')], max_length=55, verbose_name=''),
        ),
    ]
