# Generated by Django 3.1.7 on 2021-03-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0007_auto_20210324_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.CharField(default=100203, max_length=255, verbose_name='Номер лицевого счёта'),
            preserve_default=False,
        ),
    ]
