# Generated by Django 3.1.7 on 2021-03-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_db', '0008_account_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfertype',
            name='transfer_income',
            field=models.CharField(choices=[('Приход', 'Income'), ('Расход', 'Outcome')], max_length=55, verbose_name=''),
        ),
    ]
